crm/operation/client/urls.py
from django.urls import path
from .views import HomeClientView, ClientListView, ClientDetailView


app_name = 'client'

urlpatterns = [
    path('list/', HomeClientView.as_view(), name='client-list'),
    path('clients_json/', ClientListView.as_view(), name='client-json'),
    path('<int:pk>/', ClientDetailView.as_view(), name='client-detail'),
    # path('<int:pk>/update/', LeadUpdateView.as_view(), name='update'),   

]

crm/operation/deal/urls.py
from django.urls import path
from .views import HomeDealView, DealListView, DealDetailView, DealUpdateView, DealDeleteView, DealHomeTaskView, DealTaskListView, DealTaskDetailView, DealTaskUpdateView, DealTaskDeleteView, DealTaskCreateView

app_name = 'deal'

urlpatterns = [
    path('list/', HomeDealView.as_view(), name='list'),
    path('deals_json/', DealListView.as_view(), name='deal-json'),
    # path('create/', DealCreateView.as_view(), name='create'),
    path('<int:pk>/', DealDetailView.as_view(), name='detail'),
    path('<int:pk>/update/', DealUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', DealDeleteView.as_view(), name='delete'),

    path('task/list/', DealHomeTaskView.as_view(), name='task-list'),
    path('tasks_json/', DealTaskListView.as_view(), name='task-json'),
    path('<int:deal_pk>/task/create/', DealTaskCreateView.as_view(), name='task-create'),
    path('task/<int:pk>/', DealTaskDetailView.as_view(), name='task-detail'),
    path('task/<int:pk>/update/', DealTaskUpdateView.as_view(), name='task-update'),
    path('task/<int:pk>/delete/', DealTaskDeleteView.as_view(), name='task-delete'),
]

crm/operation/lead/urls.py
from django.urls import path
from .views import HomeLeadView, LeadListView, LeadCreateView, LeadUpdateView, LeadDetailView, LeadDeleteView, LeadTaskCreateView, LeadHomeTaskView, LeadTaskListView, LeadTaskDetailView, LeadTaskDeleteView, LeadTaskUpdateView, convert_lead_to_deal

app_name = 'lead'

urlpatterns = [
    path('list/', HomeLeadView.as_view(), name='list'),
    path('leads_json/', LeadListView.as_view(), name='lead-json'),
    path('create/', LeadCreateView.as_view(), name='create'),
    path('<int:pk>/', LeadDetailView.as_view(), name='detail'),
    path('<int:pk>/update/', LeadUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', LeadDeleteView.as_view(), name='delete'),
    path('converted_to_deal/<int:pk>/', convert_lead_to_deal, name='converted-to-deal'),


    path('task/list/', LeadHomeTaskView.as_view(), name='task-list'),
    path('tasks_json/', LeadTaskListView.as_view(), name='task-json'),
    path('<int:lead_pk>/task/create/', LeadTaskCreateView.as_view(), name='task-create'),
    path('task/<int:pk>/', LeadTaskDetailView.as_view(), name='task-detail'),
    path('task/<int:pk>/update/', LeadTaskUpdateView.as_view(), name='task-update'),
    path('task/<int:pk>/delete/', LeadTaskDeleteView.as_view(), name='task-delete'),

]

crm/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('administration.core.urls')),
    path('<slug:organization_slug>/media/', include('administration.organization.urls')),
    path('', include('operation.dashboard.urls')),
    path('<slug:organization_slug>/dashboard/', include('operation.dashboard.urls')),

    path('<slug:organization_slug>/configuration/country/', include('configuration.country.urls')),
    path('<slug:organization_slug>/configuration/currency/', include('configuration.currency.urls')),

    path('<slug:organization_slug>/lead/', include('operation.lead.urls')),
    path('<slug:organization_slug>/deal/', include('operation.deal.urls')),
    path('<slug:organization_slug>/contact/', include('operation.contact.urls')),
    path('<slug:organization_slug>/company/', include('operation.company.urls')),
    path('<slug:organization_slug>/client/', include('operation.client.urls')),
    path('<slug:organization_slug>/product/', include('configuration.product.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crm/operation/deal/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from django.core.validators import MaxLengthValidator

from configuration.country.models import Country
from administration.organization.models import Organization
from configuration.currency.models import Currency
from configuration.product.models import Product
from operation.company.models import Company
from operation.client.models import Client


def get_sentinel_user():
    user, created = User.objects.get_or_create(username="deleted")
    if created:
        user.set_unusable_password()
        user.save()
    return user


class Deal(models.Model):
    deal_name = models.CharField(max_length=100, unique=True, blank=False, null=True)
    DEAL_SOURCE_CHOICES = [
        ('website', 'Website'),
        ('whatsapp', 'Whatsapp'),
        ('direct_mail', 'Direct Mail'),
        ('phone_call', 'Phone Call'),
        ('in_person', 'In Person'),
        ('social_media', 'Social Media'),
    ]
    deal_source = models.CharField(max_length=50, choices=DEAL_SOURCE_CHOICES)

    client = models.ForeignKey(Client, on_delete=models.SET_NULL, null=True, blank=True, related_name='client_deals')
    primary_email = models.EmailField(blank=False)
    first_name = models.CharField(max_length=100, blank=False)
    last_name = models.CharField(max_length=100, blank=False)
    TITLE_CHOICES = [
        ('ceo', 'CEO'),
        ('company_rep', 'Company Representative'),
        ('independent_professional', 'Independent Professional'),
        ('entrepreneur', 'Entrepreneur'),
        ('student', 'Student'),
    ]
    title = models.CharField(max_length=50, choices=TITLE_CHOICES)
    phone = models.CharField(max_length=20, blank=True)
    mobile_phone = models.CharField(max_length=20, blank=True)

    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name='company_deals', null=True, blank=True)
    company_name = models.CharField(max_length=255)
    company_email = models.EmailField(blank=False)
    company_phone = models.CharField(max_length=20, blank=True)
    website = models.URLField(blank=True)
    INDUSTRY_CHOICES = [
        ('public', 'Public'),
        ('private', 'Private'),
        ('non_profit', 'Non-Profit'),
    ]
    industry = models.CharField(max_length=20, choices=INDUSTRY_CHOICES)

    country = models.ForeignKey(
        Country, on_delete=models.SET_NULL, blank=False, null=True, limit_choices_to={'is_selected': True})
    currency = models.ForeignKey(Currency, on_delete=models.SET_NULL, null=True)  

    description = models.TextField(validators=[MaxLengthValidator(280)])

    assigned_to = models.ForeignKey(User, related_name='assigned_deal', on_delete=models.SET(get_sentinel_user))
    created_by = models.ForeignKey(User, related_name='created_deal', on_delete=models.SET(get_sentinel_user))
    last_modified_by = models.ForeignKey(User, related_name='last_modified_deal', on_delete=models.SET(get_sentinel_user))

    created_time = models.DateTimeField(auto_now_add=True)
    modified_time = models.DateTimeField(auto_now=True)
    start_date_time = models.DateTimeField(null=True, blank=True, help_text="Please use the following format: <em>YYYY-MM-DD</em>.")
    end_date_time = models.DateTimeField(null=True, blank=True, help_text="Please use the following format: <em>YYYY-MM-DD</em>.")
    extended_end_date_time = models.DateTimeField(null=True, blank=True, help_text="Please use the following format: <em>YYYY-MM-DD</em>.")    
    actual_completion_date = models.DateTimeField(null=True, blank=True)
    
    organization = models.ForeignKey(Organization, related_name='deal', on_delete=models.CASCADE)    
    
    STAGE_CHOICES = [
        ('new', 'New'),
        ('in_progress', 'In Progress'),
        ('dorman', 'Dorman'),
        ('close_win', 'Close Win'),
        ('close_lost', 'Close Lost'),
    ]
    stage = models.CharField(max_length=20, choices=STAGE_CHOICES, default='new')
    is_closed = models.BooleanField(default=False)  
    erased = models.BooleanField(default=False)

    def clean(self):
        super().clean()
        self.deal_name = self.deal_name.title()
        self.first_name = self.first_name.title()
        self.last_name = self.last_name.title()

    def __str__(self):
        return self.deal_name
    
    def save(self, *args, **kwargs):
        if self.website:
            if self.website.startswith('http://'):
                # Reemplazar http:// por https://
                self.website = 'https://' + self.website[len('http://'):]
            elif not self.website.startswith('https://'):
                # Añadir https:// si no comienza con http:// o https://
                self.website = 'https://' + self.website

        if self.website and not self.website.startswith('https://'):
            self.website = 'https://' + self.website
        super().save(*args, **kwargs)


class DealProduct(models.Model):
    deal = models.ForeignKey(
        Deal, related_name='deal_product', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='deal_product', on_delete=models.CASCADE)
    cotizacion_url = models.URLField(null=True, blank=True)

    def __str__(self):
        return self.product.name


class DealTask(models.Model):
    name = models.CharField(max_length=200, blank=False)
    deal = models.ForeignKey('Deal', related_name='deal_dealtask', on_delete=models.CASCADE, null=True, blank=True)
    deal_product = models.ForeignKey('DealProduct', related_name='product_dealtask', on_delete=models.CASCADE, null=True, blank=True)
    parent_task = models.ForeignKey('self', null=True, blank=True, related_name='parent_dealtask', on_delete=models.CASCADE)
    description = models.TextField()
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='created_dealtask', on_delete=models.CASCADE)
    created_time = models.DateTimeField(auto_now_add=True)
    modified_time = models.DateTimeField(auto_now=True)
    assigned_to = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='assigned_dealtask', on_delete=models.CASCADE)
    last_modified_by = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='modified_dealtask', on_delete=models.CASCADE)
    organization = models.ForeignKey(Organization, related_name='organization_dealtask', on_delete=models.CASCADE)
    STAGE_CHOICES = [
        ('pending', 'Pending'),
        ('in_progress', 'In Progress'),
        ('completed', 'Completed'),
        ('canceled', 'Canceled'),
    ]   
    stage = models.CharField(max_length=20, choices=STAGE_CHOICES, default='pending')    
    is_closed = models.BooleanField(default=False)

    def clean(self):
        super().clean()
        self.name = self.name.title()

    def __str__(self):
        return self.name

crm/operation/lead/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from django.core.validators import MaxLengthValidator

from configuration.country.models import Country
from administration.organization.models import Organization
from configuration.currency.models import Currency
from configuration.product.models import Product
from operation.company.models import Company
from operation.contact.models import Contact


def get_sentinel_user():
    user, created = User.objects.get_or_create(username="deleted")
    if created:
        user.set_unusable_password()
        user.save()
    return user


class Lead(models.Model):
    lead_name = models.CharField(max_length=100, unique=True, blank=False, null=True)
    LEAD_SOURCE_CHOICES = [
        ('website', 'Website'),
        ('whatsapp', 'Whatsapp'),
        ('direct_mail', 'Direct Mail'),
        ('phone_call', 'Phone Call'),
        ('in_person', 'In Person'),
        ('social_media', 'Social Media'),
    ]
    lead_source = models.CharField(max_length=50, choices=LEAD_SOURCE_CHOICES)

    contact = models.ForeignKey(Contact, on_delete=models.SET_NULL, null=True, blank=True, related_name='contact_leads')    
    primary_email = models.EmailField(blank=False)
    first_name = models.CharField(max_length=100, blank=False)
    last_name = models.CharField(max_length=100, blank=False)
    TITLE_CHOICES = [
        ('ceo', 'CEO'),
        ('company_rep', 'Company Representative'),
        ('independent_professional', 'Independent Professional'),
        ('entrepreneur', 'Entrepreneur'),
        ('student', 'Student'),
    ]
    title = models.CharField(max_length=50, choices=TITLE_CHOICES)
    phone = models.CharField(max_length=20, blank=True)
    mobile_phone = models.CharField(max_length=20, blank=True)

    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name='company_leads', null=True, blank=True)
    company_name = models.CharField(max_length=255)
    company_email = models.EmailField(blank=False)
    company_phone = models.CharField(max_length=20, blank=True)
    website = models.URLField(blank=True)
    INDUSTRY_CHOICES = [
        ('public', 'Public'),
        ('private', 'Private'),
        ('non_profit', 'Non-Profit'),
    ]
    industry = models.CharField(max_length=20, choices=INDUSTRY_CHOICES)
    
    country = models.ForeignKey(
        Country, on_delete=models.SET_NULL, blank=False, null=True, limit_choices_to={'is_selected': True})
    currency = models.ForeignKey(Currency, on_delete=models.SET_NULL, null=True)
    
    description = models.TextField(validators=[MaxLengthValidator(280)])

    assigned_to = models.ForeignKey(User, related_name='assigned_lead', on_delete=models.SET(get_sentinel_user))
    created_by = models.ForeignKey(User, related_name='created_lead', on_delete=models.SET(get_sentinel_user))
    last_modified_by = models.ForeignKey(User, related_name='last_modified_lead', on_delete=models.SET(get_sentinel_user))

    created_time = models.DateTimeField(auto_now_add=True)
    modified_time = models.DateTimeField(auto_now=True)
    start_date_time = models.DateTimeField(null=True, blank=True, help_text="Please use the following format: <em>YYYY-MM-DD</em>.")
    end_date_time = models.DateTimeField(null=True, blank=True, help_text="Please use the following format: <em>YYYY-MM-DD</em>.")
    extended_end_date_time = models.DateTimeField(null=True, blank=True, help_text="Please use the following format: <em>YYYY-MM-DD</em>.")    
    actual_completion_date = models.DateTimeField(null=True, blank=True)

    organization = models.ForeignKey(Organization, related_name='lead', on_delete=models.CASCADE)  

    STAGE_CHOICES = [
        ('new', 'New'),
        ('in_progress', 'In Progress'),
        ('dorman', 'Dorman'),
        ('close_lost', 'Close Lost'),
    ]  
    stage = models.CharField(max_length=20, choices=STAGE_CHOICES, default='new')
    is_closed = models.BooleanField(default=False) 
    erased = models.BooleanField(default=False)

    def clean(self):
        super().clean()
        self.lead_name = self.lead_name.title()
        self.first_name = self.first_name.title()
        self.last_name = self.last_name.title()

    def __str__(self):       
        return self.lead_name  
    
    def save(self, *args, **kwargs):
        if self.website:
            if self.website.startswith('http://'):
                # Reemplazar http:// por https://
                self.website = 'https://' + self.website[len('http://'):]
            elif not self.website.startswith('https://'):
                # Añadir https:// si no comienza con http:// o https://
                self.website = 'https://' + self.website

        if self.website and not self.website.startswith('https://'):
            self.website = 'https://' + self.website
        super().save(*args, **kwargs)


class LeadProduct(models.Model):
    lead = models.ForeignKey(
        Lead, related_name='lead_product', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='lead_product', on_delete=models.CASCADE)
    cotizacion_url = models.URLField(null=True, blank=True)

    def __str__(self):
        return self.product.name


class LeadTask(models.Model):
    name = models.CharField(max_length=200, blank=False)
    lead = models.ForeignKey('Lead', related_name='lead_leadtask', on_delete=models.CASCADE, null=True, blank=True)
    lead_product = models.ForeignKey('LeadProduct', related_name='product_leadtask', on_delete=models.CASCADE, null=True, blank=True)
    parent_task = models.ForeignKey('self', null=True, blank=True, related_name='parent_leadtask', on_delete=models.CASCADE)
    description = models.TextField()
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='created_leadtask', on_delete=models.CASCADE)
    created_time = models.DateTimeField(auto_now_add=True)
    modified_time = models.DateTimeField(auto_now=True)
    assigned_to = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='assigned_leadtask', on_delete=models.CASCADE)
    last_modified_by = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='modified_leadtask', on_delete=models.CASCADE)
    organization = models.ForeignKey(Organization, related_name='organization_leadtask', on_delete=models.CASCADE)    
    STAGE_CHOICES = [
        ('pending', 'Pending'),
        ('in_progress', 'In Progress'),
        ('completed', 'Completed'),
        ('canceled', 'Canceled'),
    ]
    stage = models.CharField(max_length=20, choices=STAGE_CHOICES, default='pending')    
    is_closed = models.BooleanField(default=False)

    def clean(self):
        super().clean()
        self.name = self.name.title()

    def __str__(self):
        return self.name

crm/templates/operation/leadtask/task_create.html
{% extends "administration/core/base.html" %}
{% load static %}

{% block title %} {{ titulo }} {% endblock %}


{% block content %}

<div class="container rounded shadow-sm bg-light border border-2 p-5 my-4" style="width: 40%;">

    <form action="." method="post" enctype="multipart/form-data" class="row g-3">
        {% csrf_token %}
        <div class="row mb-3">
            <div class="col-12">
                <label for="formGroupExampleInput2" class="form-label">Task Nombre</label>
                {{ form.name }}
            </div>
        </div>
        <div class="row mb-3">

            <div class="col-md-5">
                <label for="formGroupExampleInput2" class="form-label">Product</label>
                {{ form.lead_product }}
            </div>
        </div>
        {% if form.parent_task %}               
            <div class="row mb-3">
                <div class="col-12">            
                    <label for="formGroupExampleInput2" class="form-label">Parent Task</label>
                    {{ form.parent_task }}
                    <input type="hidden" name="parent_task_id" value="{{ request.GET.parent_task }}"> <!-- Captura parent_task enviado por la URL desde LeadTaskUpdateView -->
                </div>
            </div>
        {% endif %}


        <div class="row mb-3">
            <div class="col-8">
                <label for="formGroupExampleInput2" class="form-label">Assigned to</label>
                {{ form.assigned_to }}
            </div>
        </div>

        <div class="row mb-3">
            <div class="col-12">
                <label for="formGroupExampleInput2" class="form-label">Description</label>
                {{ form.description }}
            </div>
        </div>

        <div class="row my-4">
            <div class="btn-group">
                <button type="button" onclick="window.history.back();" class="btn btn-secondary">Return</button> 
                <button type="submit" class="btn btn-primary">Create</button>
            </div>
        </div>

    </form>

</div>

{% endblock %}

{% block scripts %}

<script type="text/javascript">
    $(document).ready(function() {
        $('#id_related_task').change(function() {
            adjustParentTaskOptions();
        });

        function adjustParentTaskOptions() {
            var selectedRelatedTask = $('#id_related_task').val();
            $('#id_parent_task option').each(function() {
                if ($(this).val() === selectedRelatedTask) {
                    $(this).hide(); // Oculta la opción que coincide
                } else {
                    $(this).show(); // Muestra las otras opciones
                }
            });
        }
    });
</script>

{% endblock %}

crm/templates/operation/leadtask/task_delete.html
{% extends "administration/core/base.html" %}
{% load static %}

{% block title %}{{ titulo }}{% endblock %}

{% block content %}

<div class="col-sm-6 col-md-6 col-lg-6 col-xl-6 mx-auto my-5">
    <div class="card">
        <h5 class="card-header">Lead {{ lead_name }}</h5>
        <div class="card-body">
            <h5 class="card-title">Are you sure you want to delete {{ task.name }}?</h5>
            <br>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="button" onclick="window.history.back();" class="btn btn-secondary">Return</button> 
                <button type="submit" class="btn btn-danger">Delete</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

crm/templates/operation/leadtask/task_detail.html
{% extends "administration/core/base.html" %}

{% block title %}{% endblock %}

{% block content %}

<div class="card" style="width: 22rem;">
    <div class="card-header">
        <h2> <a href="{% url 'lead:detail' pk=task.lead.id organization_slug=organization_slug %}">{{ task.lead }} - lead id: {{ task.lead.id }}</a></h2>
    </div>
    <ul class="list-group list-group-flush">
        <span class="badge bg-secondary">Assigned to</span>
        <li class="list-group-item">{{ task.assigned_to }} </li>
        <span class="badge bg-secondary">Created By</span>
        <li class="list-group-item">{{ task.created_by }} </li>
        <span class="badge bg-secondary">Created At</span>
        <li class="list-group-item">{{ task.created_time }} </li>
        {% if task_product %}
        <span class="badge bg-secondary">Producto</span>
            <li class="list-group-item">{{ task_product }}</li>            
        {% else %}
            <li class="list-group-item">No products associated with this task.</li>
        {% endif %}    
        <span class="badge bg-success">Stage</span>     
        <li class="list-group-item">{{ task.stage }}   </li> 
        
        {% if subtasks %}
            <span class="badge bg-info">SubTareas</span>
            {% for subtask in subtasks %}
            <li class="list-group-item">
                <a href="{% url 'lead:task-detail' pk=subtask.pk organization_slug=organization_slug %}">{{ subtask.name }}</a>
            </li>
            {% endfor %}
        {% elif parent_task %}
            <span class="badge bg-warning">Parent Task</span>
            <li class="list-group-item">
                <a href="{% url 'lead:task-detail' pk=parent_task.pk organization_slug=organization_slug %}">{{ parent_task.name }}</a>
            </li>
        {% endif %}

    </ul>
</div>
<div>
    <a href="{% url 'lead:task-update' pk=task.pk organization_slug=organization_slug %}" class="btn btn-primary">Update</a>
    <a href="{% url 'lead:task-delete' pk=task.pk organization_slug=organization_slug %}" class="btn btn-danger mt-3">Delete</a>
</div>
<div class="col-md-8 mt-3">

</div>
                

{% endblock %}

crm/templates/operation/leadtask/task_update.html
{% extends "administration/core/base.html" %}
{% load static %}

{% block title %} {{ titulo }} {% endblock %}


{% block content %}

<div class="container rounded shadow-sm bg-light border border-2 p-5 my-4" style="width: 40%;">

    <form id="taskUpdateForm" action="." method="post" enctype="multipart/form-data" class="row g-3">
        {% csrf_token %}
        <div class="row mb-3">
            <div class="col-12">
                <label for="id_name" class="form-label">Task Nombre</label>
                {{ form.name }}
            </div>
        </div>
        <div class="row mb-3">
            <div class="col-12">
                <label for="id_lead_product" class="form-label">Product</label>
                {{ form.lead_product }}
            </div>
        </div>
        <div class="row mb-3">
            <div class="col-12">
                <label for="id_parent_task" class="form-label">Parent Task</label>
                {{ form.parent_task }}
            </div>
        </div>

        <div class="row mb-3">
            <div class="col-8">
                <label for="id_assigned_to" class="form-label">Assigned to</label>
                {{ form.assigned_to }}
            </div>
        </div>

        <div class="row mb-3">
            <div class="col-8">
                <label for="id_stage" class="form-label">Stage</label>
                {{ form.stage }}
            </div>
        </div>

        <div class="row mb-3">
            <div class="col-12">
                <label for="id_description" class="form-label">Description</label>
                {{ form.description }}
            </div>
        </div>

       <br>    
            
        <div class="row my-4">
            <div class="btn-group">
                <button type="button" onclick="window.history.back();" class="btn btn-secondary">Return</button> 
                <a id="addSubtaskButton" href="{% url 'lead:task-create' organization_slug=organization_slug lead_pk=lead.id  %}?parent_task={{ pk }}" class="btn btn-success {% if not enable_button %}disabled{% endif %}" {% if not enable_button %}onclick="return false;" {% endif %}>Add Subtask</a>
                <button id="buttonSubmitTaskUpdate" type="submit" class="btn btn-primary">Update</button>
            </div>
        </div>

    </form>

</div>
{% endblock %}





{% block scripts %}


<script>
    //Oculta el boton Add Subtask si se tiene seleccionado una opcion del select de parent_task
    document.addEventListener('DOMContentLoaded', function () {
        const parentTaskSelect = document.getElementById('id_parent_task');
        const addSubtaskButton = document.getElementById('addSubtaskButton');
    
        function toggleAddSubtaskButton() {
            // Ocultar el botón si se ha seleccionado un parent task
            if (parentTaskSelect.value) {
                addSubtaskButton.style.display = 'none';
            } else {
                addSubtaskButton.style.display = 'inline-block';
            }
        }
    
        // Escuchar cambios en el campo select de parent task
        parentTaskSelect.addEventListener('change', toggleAddSubtaskButton);
    
        // Llamada inicial para establecer el estado correcto del botón
        toggleAddSubtaskButton();
    });
</script>
    

<script>
    // Validaciones basadas en el estado del Lead
    $(document).ready(function() {
        
        var isLeadClosed = {{ is_lead_closed|yesno:"true,false" }};
        var isTaskClosed = {{ is_task_closed|yesno:"true,false" }};
        var extendedEndDate = "{{ extended_end_date_time|date:"Y-m-d H:i:s" }}";
        var endDate = "{{ end_date_time|date:"Y-m-d H:i:s" }}";
        var current_time = new Date();
        
        if (isLeadClosed) {
            disableFormFields();
        }
    
        // Validaciones basadas en el estado de la tarea
        if (isTaskClosed) {
            disableFormFields();
        }
        
        // Validaciones basadas en las fechas de cierre del Lead
        if (extendedEndDate && new Date(extendedEndDate) < current_time) {
            disableFormFields();
            console.log('inside extended end date');
        } else if (endDate && new Date(endDate) < current_time && !extendedEndDate) {
            disableFormFields();
        }
        
        function disableFormFields() {
            // Deshabilita todos los campos de entrada, select y textarea dentro del formulario
            $("#taskUpdateForm input, #taskUpdateForm select, #taskUpdateForm textarea").prop('disabled', true);
            
            // Deshabilita el botón de submit
            $("#buttonSubmitTaskUpdate").prop('disabled', true);
            $("#addSubtaskButton").prop('disabled', true);
        }          
        
        // evita que las tareas de related task esten en las opciones de parent task
        $('#id_related_task').change(function() {
            adjustParentTaskOptions();
        });
        
        function adjustParentTaskOptions() {
            var selectedRelatedTask = $('#id_related_task').val();
            
            $('#id_parent_task option').each(function() {
                if ($(this).val() === selectedRelatedTask) {
                    $(this).hide(); // Oculta la opción que coincide
                } else {
                    $(this).show(); // Muestra las otras opciones
                }
            });
        }

            // Llama a adjustParentTaskOptions en la carga inicial en caso de que relatedTask tenga un valor preestablecido
            adjustParentTaskOptions();

    }); 


</script>

    
{% endblock %}